version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: birdloggr.app

- url: /(.)(.*)
  static_files: resources/\1\2
  upload: resources/(.*)

- url: /
  static_files: resources/index.html
  upload: resources/index.html